name: Hello, World!
on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with: 
        go-version: 1.13

    - name: git clone this repository
      uses: actions/checkout@v1

    - name: Print where you are
      run: ls

    - name: Print where you are
      run: pwd

    - name: Run Test Case
      run: go test -v .
